
[target.aarch64-linux-android]
ar = "/e/rustNDK/28_arm64/bin/aarch64-linux-android-ar"
linker = "/e/rustNDK/28_arm64/bin/aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
ar = "/e/rustNDK/28_arm/bin/arm-linux-androideabi-ar"
linker = "/e/rustNDK/28_arm/bin/arm-linux-androideabi-clang"

[target.i686-linux-android]
ar = "/e/rustNDK/28_x86/bin/i686-linux-android-ar"
linker = "/e/rustNDK/28_x86/bin/i686-linux-android-clang"

[target.x86_64-linux-android]
ar = "/e/rustNDK/28_x86_64/bin/x86_64-linux-android-ar"
linker = "/e/rustNDK/28_x86_64/bin/x86_64-linux-android-clang"

[target.x86_64-unknown-linux-gnu]
ar = "/usr/bin/x86_64-linux-gnu-ar"
linker = "/usr/bin/clang"

[target.x86_64-unknown-linux-musl]
ar = "/usr/bin/x86_64-linux-gnu-ar"
linker = "/usr/bin/clang"

[target.i686-unknown-linux-musl]
ar = "/usr/bin/x86_64-linux-gnu-ar"
linker = "/usr/bin/clang"

